changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
    authors:
      - dependabot[bot]
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Performance
      labels:
        - performance
    - title: Other changes
      labels:
        - "*"
