[package]
name = "peaky-geo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
geo.workspace = true
geojson.workspace = true
geozero = { version = "0.14", default-features = false, features = ["with-geo", "with-wkb"] }
peaky-preset.workspace = true
rayon.workspace = true
reqwest.workspace = true
tracing.workspace = true
rstar.workspace = true
serde.workspace = true
serde_json.workspace = true
splatter.workspace = true
tempfile.workspace = true
thiserror.workspace = true
quick-xml.workspace = true
zip.workspace = true
