[package]
name = "peaky"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "peaky"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
peaky-finder.workspace = true
peaky-freeze.workspace = true
peaky-geo.workspace = true
peaky-peaks.workspace = true
peaky-preset.workspace = true
peaky-serve.workspace = true
peaky-map.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
