"""Mesh-backbone link geometry and preset config."""

from peaky_finders.site_suggestions.context import BackboneSite, SiteSuggestionContext
from peaky_finders.site_suggestions.mesh_backbone_completion import (
    LinkCompletionResult,
    all_backbone_sites,
    all_links_complete,
    backbone_sites_from_preset,
    endpoint_slugs_in_zone,
    evaluate_link_completion,
    evaluate_mesh_backbone_completion,
    footprints_for_backbone_sites,
    hop_adjacency,
    mesh_backbone_planning_complete,
    order_sites_along_leg,
    position_along_leg_m,
    sites_in_zone,
)
from peaky_finders.site_suggestions.mesh_backbone_geom import (
    AnchorPoint,
    anchor_from_site,
    anchors_from_preset,
    build_link_leg,
    distance_to_link_m,
    link_search_zone,
    resolve_link_leg,
    resolved_link_legs,
    sample_along_link,
    validate_mesh_backbone_site_slugs,
)

__all__ = [
    "AnchorPoint",
    "BackboneSite",
    "LinkCompletionResult",
    "SiteSuggestionContext",
    "all_backbone_sites",
    "all_links_complete",
    "anchor_from_site",
    "anchors_from_preset",
    "backbone_sites_from_preset",
    "build_link_leg",
    "distance_to_link_m",
    "endpoint_slugs_in_zone",
    "evaluate_link_completion",
    "evaluate_mesh_backbone_completion",
    "footprints_for_backbone_sites",
    "hop_adjacency",
    "link_search_zone",
    "mesh_backbone_planning_complete",
    "order_sites_along_leg",
    "position_along_leg_m",
    "resolve_link_leg",
    "resolved_link_legs",
    "sample_along_link",
    "sites_in_zone",
    "validate_mesh_backbone_site_slugs",
]
