"""Generate a configure-style Makefile from a preset YAML.

``peaky generate-makefile``: resolve preset + bundle inputs to ``BUILD``
paths under ``<preset>/build`` (clips, DEM, bundles, stamps) with stamp edges.

Build subtrees use stable paths under ``<preset>/build``; content fingerprints live in
stamps, clip manifests, and ``bundle/resolve.json``.

Bundle Makefile recipes use ``&:`` grouped targets where applicable (GNU Make 4.3+).
"""

from __future__ import annotations

from pathlib import Path

from peaky_finders.build_configure import (
    BuildConfigurePlan,
    PlannedClipLayer,
    PlannedMeshPair,
    PlannedViewshedWorkspace,
    configure_preset_build,
    make_var_token,
)


def _path_for_makefile(path: Path, *, make_root: Path) -> str:
    resolved = path.expanduser().resolve()
    root = make_root.expanduser().resolve()
    try:
        return resolved.relative_to(root).as_posix()
    except ValueError:
        return resolved.as_posix()


def _rel(plan: BuildConfigurePlan, path: Path) -> str:
    return _path_for_makefile(path, make_root=plan.make_root)


def _clip_var(layer: PlannedClipLayer, index: int) -> str:
    role = make_var_token(layer.role)
    layer_part = make_var_token(layer.layer)
    return f"CLIP_{role}_{layer_part}_{index}"


def _viewshed_var(ws: PlannedViewshedWorkspace) -> str:
    return f"VIEWSHED_{make_var_token(ws.rep_slug)}"


def _mesh_pair_var(pair: PlannedMeshPair) -> str:
    return f"MESH_PAIR_{make_var_token(pair.slug_a)}_{make_var_token(pair.slug_b)}"


def _stamp_make_var(section: str) -> str:
    """Makefile variable stem for stamp ``section`` (e.g. ``site__hub`` → ``STAMP_SITE_HUB``)."""
    return f"STAMP_{make_var_token(section)}"


def _bundle_stamp_for_clip_role(role: str) -> str:
    mapping = {"aoi": "bundle_aoi", "include": "bundle_include", "exclude": "bundle_exclude"}
    return mapping[role]


def _stamp_rel_path(plan: BuildConfigurePlan, section: str) -> str:
    safe = section.replace("/", "__")
    p = plan.preset_build_root / "stamps" / f"{safe}.sha"
    return _rel(plan, p)


def _dem_prereq_vars(dem_vars: list[str]) -> str:
    """Space-prefixed prereq list: enumerated DEM tile files, or ``dem-tiles`` before configure sees tiles."""
    if dem_vars:
        return " " + " ".join(f"$({v})" for v in dem_vars)
    return " dem-tiles"


def _sorted_unique_input_paths(
    layers: tuple[PlannedClipLayer, ...],
    *,
    roles: tuple[str, ...] | None = None,
) -> tuple[Path, ...]:
    role_set = None if roles is None else set(roles)
    paths: set[Path] = set()
    for layer in layers:
        if role_set is not None and layer.role not in role_set:
            continue
        paths.update(layer.input_files)
    return tuple(sorted(paths, key=lambda p: p.as_posix()))


def _stamp_bundle_input_paths(plan: BuildConfigurePlan, section: str) -> tuple[Path, ...]:
    if section == "bundle_aoi":
        return _sorted_unique_input_paths(plan.clip_layers, roles=("aoi",))
    if section == "bundle_include":
        return _sorted_unique_input_paths(plan.clip_layers, roles=("include",))
    if section == "bundle_exclude":
        return _sorted_unique_input_paths(plan.clip_layers, roles=("exclude",))
    if section == "bundle_land_use":
        return _sorted_unique_input_paths(plan.clip_layers, roles=("include", "exclude"))
    return ()


def _makefile_prereq_paths(plan: BuildConfigurePlan, paths: tuple[Path, ...]) -> str:
    if not paths:
        return ""
    return " " + " ".join(_rel(plan, p) for p in paths)


def build_makefile_text(*, plan: BuildConfigurePlan, preset_arg: str) -> str:
    lines: list[str] = [
        "# Generated by peaky generate-makefile (configure) — do not edit by hand.",
        f"# Regenerate: {plan.peaky_cmd} generate-makefile {preset_arg}",
        "",
        f"PEAKY ?= {plan.peaky_cmd}",
        f"PRESET ?= {plan.preset_rel}",
        f"SLUG ?= {plan.slug}",
        f"KMZ ?= {_rel(plan, plan.kmz)}",
        "",
        f"BUILD ?= {_rel(plan, plan.preset_build_root)}",
        f"CLIPS ?= {_rel(plan, plan.clips_root)}",
        f"BUNDLES ?= {_rel(plan, plan.bundles_root)}",
        f"VIEWSHEDS ?= {_rel(plan, plan.viewsheds_root)}",
        f"SPLAT_TILES ?= {_rel(plan, plan.splat_tiles_root)}",
        f"MESH_PAIRWISE ?= {_rel(plan, plan.mesh_pairwise_root)}",
        f"MESH_DEPTH ?= {_rel(plan, plan.mesh_depth_root)}",
        f"ELIGIBLE_UNION_ROOT ?= {_rel(plan, plan.eligible_union_root)}",
        f"PLSS_CACHE ?= {_rel(plan, plan.plss_cache)}",
        "",
    ]

    if plan.has_bundle:
        lines.extend(
            [
                f"BUNDLE_RESOLVE ?= {_rel(plan, plan.bundle_resolve)}",
                "",
            ]
        )

    clip_vars: list[str] = []
    for idx, layer in enumerate(plan.clip_layers):
        var = _clip_var(layer, idx)
        clip_vars.append(var)
        lines.append(f"{var} ?= {_rel(plan, layer.gpkg)}")

    composite_vars: dict[str, str] = {}
    if plan.composites:
        lines.append("")
        for comp in plan.composites:
            var = f"COMPOSITE_{make_var_token(comp.role)}"
            composite_vars[comp.role] = var
            lines.append(f"{var} ?= {_rel(plan, comp.union_gpkg)}")

    elig_slice_vars: list[str] = []
    if plan.eligible_slice_kml_paths:
        lines.append("")
        lines.append("# Eligible per-include overlays (paired with COMPOSITE_ELIGIBLE via &: below)")
        for idx, sp in enumerate(plan.eligible_slice_kml_paths):
            var = f"ELIG_LAYER_{idx}"
            elig_slice_vars.append(var)
            lines.append(f"{var} ?= {_rel(plan, sp)}")

    ref_vars: list[str] = []
    if plan.references:
        lines.append("")
        for ref in plan.references:
            var = f"REF_{make_var_token(ref.entry_id)}"
            ref_vars.append(var)
            lines.append(f"{var} ?= {_rel(plan, ref.gpkg)}")

    ws_vars: dict[str, str] = {}
    site_to_ws_var: dict[str, str] = {}
    if plan.viewshed_workspaces:
        lines.append("")
        lines.append("# Propagation workspaces (slug-named dirs under VIEWSHEDS; stamped via simulation + sites/*)")
        for ws in plan.viewshed_workspaces:
            var = _viewshed_var(ws)
            ws_vars[ws.rep_slug] = var
            lines.append(f"{var}_REQUEST ?= {_rel(plan, ws.request_json)}")
            lines.append(f"{var}_PPM ?= {_rel(plan, ws.output_ppm)}")
            lines.append(f"{var}_PNG ?= {_rel(plan, ws.splat_png)}")
            lines.append(f"{var}_GPKG ?= {_rel(plan, ws.coverage_gpkg)}")
            lines.append(f"{var}_DIR ?= {_rel(plan, ws.workdir)}")
            slug_comment = ", ".join(ws.site_slugs)
            lines.append(f"#   sites: {slug_comment}")
            for slug in ws.site_slugs:
                site_to_ws_var[slug] = var

    dem_pairs: list[tuple[str, Path]] = []
    dem_vars: list[str] = []
    if plan.dem_tiles:
        lines.append("")
        lines.append(f"# DEM mirror tiles ({len(plan.dem_tiles)} tiles at configure time)")
        for idx, tile_path in enumerate(plan.dem_tiles):
            stem = make_var_token(tile_path.name.replace(".", "_"))
            var = f"DEM_{stem}_{idx}"
            dem_vars.append(var)
            dem_pairs.append((var, tile_path))
            lines.append(f"{var} ?= {_rel(plan, tile_path)}")

    mesh_pair_vars: list[str] = []
    if plan.mesh_pairs:
        lines.append("")
        for pair in plan.mesh_pairs:
            var = _mesh_pair_var(pair)
            mesh_pair_vars.append(var)
            lines.append(f"{var} ?= {_rel(plan, pair.complete_json)}")

    mesh_depth_var: str | None = None
    if plan.mesh_depth_complete is not None:
        mesh_depth_var = "MESH_DEPTH_COMPLETE"
        lines.append("")
        lines.append(f"{mesh_depth_var} ?= {_rel(plan, plan.mesh_depth_complete)}")

    eligible_union_var: str | None = None
    if plan.eligible_union_complete is not None:
        eligible_union_var = "ELIGIBLE_UNION_COMPLETE"
        lines.append(f"{eligible_union_var} ?= {_rel(plan, plan.eligible_union_complete)}")

    lines.append("")
    lines.append("# Stamps (invalidate downstream edges)")
    stamp_var_by_section: dict[str, str] = {}
    for sec in plan.stamp_sections:
        sv = _stamp_make_var(sec)
        stamp_var_by_section[sec] = sv
        lines.append(f"{sv} ?= {_stamp_rel_path(plan, sec)}")

    lines.append("")
    for sec in plan.stamp_sections:
        sv = stamp_var_by_section[sec]
        stamp_inputs = _stamp_bundle_input_paths(plan, sec)
        lines.append(f"$({sv}): $(PRESET){_makefile_prereq_paths(plan, stamp_inputs)}")
        if sec.startswith("site__"):
            slug = sec[len("site__") :]
            lines.append(f"\t$(PEAKY) stamp site {slug} $(PRESET)")
        else:
            lines.append(f"\t$(PEAKY) stamp {sec} $(PRESET)")
        lines.append("")

    site_stamp_sections_for_plss = sorted(sec for sec in plan.stamp_sections if sec.startswith("site__"))
    plss_deps_for_kmz = False
    if site_stamp_sections_for_plss:
        plss_deps_for_kmz = True
        st_topo_plss = stamp_var_by_section["topology"]
        plss_prereqs = " ".join(
            [f"$({st_topo_plss})"]
            + [f"$({stamp_var_by_section[s]})" for s in site_stamp_sections_for_plss]
        )
        lines.append(f"$(PLSS_CACHE): {plss_prereqs}")
        lines.append("\t$(PEAKY) bundle plss $(PRESET)")
        lines.append("")

    lines.append("")
    phony = ["all"]
    if plan.has_bundle:
        phony.append("bundle")
    if plan.viewshed_workspaces:
        phony.append("viewsheds")
        phony.extend(f"viewshed/{slug}" for slug in site_to_ws_var)
    if plan.emit_mesh:
        phony.extend(["mesh", "mesh-pairwise", "mesh-depth"])
    lines.append(f".PHONY: {' '.join(phony)}")
    lines.append("")
    lines.append("all: $(KMZ)")
    lines.append("")

    if plan.has_bundle and plan.clip_layers:
        aoi_clips = [clip_vars[i] for i, layer in enumerate(plan.clip_layers) if layer.role == "aoi"]
        inc_clips = [clip_vars[i] for i, layer in enumerate(plan.clip_layers) if layer.role == "include"]
        exc_clips = [clip_vars[i] for i, layer in enumerate(plan.clip_layers) if layer.role == "exclude"]

        comp_aoi = composite_vars["aoi"]

        lines.append("# --- Bundle: clip layers → composites → resolve ---")
        for idx, layer in enumerate(plan.clip_layers):
            var = clip_vars[idx]
            bs = stamp_var_by_section[_bundle_stamp_for_clip_role(layer.role)]
            deps = [f"$({bs})", "$(PRESET)"]
            if layer.role in ("include", "exclude"):
                deps.append(f"$({comp_aoi})")
            deps.extend(_rel(plan, p) for p in layer.input_files)
            lines.append(f"$({var}): {' '.join(deps)}")
            lines.append(f"\t$(PEAKY) bundle clip {layer.role} {layer.layer} $(PRESET)")
            lines.append("")

        st_aoi = stamp_var_by_section["bundle_aoi"]
        lines.append(f"$({comp_aoi}): {' '.join(f'$({v})' for v in aoi_clips)} $({st_aoi})")
        lines.append("\t$(PEAKY) bundle composite aoi $(PRESET)")
        lines.append("")

        comp_inc = composite_vars["include"]
        st_inc = stamp_var_by_section["bundle_include"]
        lines.append(f"$({comp_inc}): {' '.join(f'$({v})' for v in inc_clips)} $({comp_aoi}) $({st_inc})")
        lines.append("\t$(PEAKY) bundle composite include $(PRESET)")
        lines.append("")

        comp_exc = composite_vars["exclude"]
        st_exc = stamp_var_by_section["bundle_exclude"]
        exc_deps = [f"$({comp_inc})"] + [f"$({v})" for v in exc_clips] + [f"$({st_exc})"]
        lines.append(f"$({comp_exc}): {' '.join(exc_deps)}")
        lines.append("\t$(PEAKY) bundle composite exclude $(PRESET)")
        lines.append("")

        comp_elig = composite_vars["eligible"]
        prereq_inc_exc = f"$({comp_inc}) $({comp_exc})"
        elig_outputs = [f"$({comp_elig})"]
        elig_outputs.extend(f"$({v})" for v in elig_slice_vars)
        grouped = " ".join(elig_outputs)
        lines.append("# Aggregated eligible + KMZ overlays (GNU Make 4.3+: &: keeps outputs in sync)")
        if len(elig_outputs) > 1:
            lines.append(f"{grouped} &: {prereq_inc_exc}")
        else:
            lines.append(f"{grouped}: {prereq_inc_exc}")
        lines.append("\t$(PEAKY) bundle eligible $(PRESET)")
        lines.append("")

        st_ref = stamp_var_by_section["bundle_reference"]
        for ref, var in zip(plan.references, ref_vars, strict=True):
            lines.append(f"$({var}): $({comp_aoi}) $({st_ref})")
            lines.append(f"\t$(PEAKY) bundle reference {ref.entry_id} $(PRESET)")
            lines.append("")

        st_top = stamp_var_by_section["topology"]
        resolve_deps = [f"$({comp_elig})"] + [f"$({v})" for v in ref_vars] + [f"$({st_top})"]
        lines.append(f"$(BUNDLE_RESOLVE): {' '.join(resolve_deps)}")
        lines.append("\t$(PEAKY) bundle resolve $(PRESET)")
        lines.append("")

        lines.append("bundle: $(BUNDLE_RESOLVE)")
        lines.append("")

        if dem_vars:
            lines.append(f"dem-tiles: {' '.join(f'$({v})' for v in dem_vars)}")
            lines.append("")
            for var, tile_path in dem_pairs:
                tile_arg = tile_path.name.removesuffix(".hgt.gz")
                lines.append(f"$({var}): $({comp_elig})")
                lines.append(f"\t$(PEAKY) bundle dem --tile {tile_arg} $(PRESET)")
                lines.append("")
        else:
            lines.append("dem-tiles: $(COMPOSITE_ELIGIBLE)")
            lines.append("\t$(PEAKY) bundle dem $(PRESET)")
            lines.append("# Re-run generate-makefile after eligible GPKG exists to enumerate DEM tiles.")
            lines.append("")

    bundle_dep = "$(BUNDLE_RESOLVE)" if plan.has_bundle else ""
    dem_dep = _dem_prereq_vars(dem_vars) if plan.has_bundle else ""

    st_sim = stamp_var_by_section["simulation"]
    st_disp = stamp_var_by_section["display"]

    if plan.viewshed_workspaces:
        lines.append("# --- Coverage: one workspace per propagation digest ---")
        for ws in plan.viewshed_workspaces:
            var = ws_vars[ws.rep_slug]
            site_stamp_deps_list = [
                f"$({stamp_var_by_section['site__' + slug]})" for slug in ws.site_slugs
            ]
            site_stamp_deps = " ".join(site_stamp_deps_list)
            parts: list[str] = [
                f"$({st_sim})",
                f"$({st_disp})",
            ]
            if site_stamp_deps:
                parts.append(site_stamp_deps)
            if bundle_dep.strip():
                parts.append(bundle_dep.strip())
            if dem_dep.strip():
                parts.append(dem_dep.strip())
            dep_line = " ".join(parts)
            lines.append(f"$({var}_REQUEST): {dep_line}")
            lines.append(
                f"\t$(PEAKY) viewshed {ws.rep_slug} $(PRESET)"
                " --workspace-only --phase request"
            )
            lines.append("")
            # PPM must not depend on request.json: GNU make leaves target mtimes unchanged
            # when a recipe is a no-op, so a REQUEST edge would re-run docker forever.
            lines.append(f"$({var}_PPM): {dep_line}")
            lines.append(
                f"\t$(PEAKY) viewshed {ws.rep_slug} $(PRESET)"
                " --workspace-only --phase docker"
            )
            lines.append("")
            lines.append(f"$({var}_PNG): $({var}_PPM)")
            lines.append(
                f"\t$(PEAKY) viewshed {ws.rep_slug} $(PRESET)"
                " --workspace-only --phase raster"
            )
            lines.append("")
            lines.append(f"$({var}_GPKG): $({var}_PPM)")
            lines.append(
                f"\t$(PEAKY) viewshed {ws.rep_slug} $(PRESET)"
                " --workspace-only --phase footprint"
            )
            lines.append("")
        for slug, var in site_to_ws_var.items():
            lines.append(f"viewshed/{slug}: $({var}_PNG) $({var}_GPKG)")
            lines.append("")

    sorted_site_png_vars: list[str] = []
    if site_to_ws_var:
        sorted_site_png_vars = [f"$({site_to_ws_var[s]}_PNG)" for s in sorted(site_to_ws_var)]

    mesh_bundle_edge = ""
    if plan.has_bundle:
        _bkml = stamp_var_by_section["bundle_kml_overlay"]
        _bmc = stamp_var_by_section["bundle_mesh_coverage"]
        mesh_bundle_edge = (
            " $(BUNDLE_RESOLVE)"
            f" $({_bkml})"
            f" $({_bmc})"
            + _dem_prereq_vars(dem_vars)
        )

    mesh_depth_extra = mesh_bundle_edge + (
        f" {' '.join(sorted_site_png_vars)}" if sorted_site_png_vars else ""
    )

    mesh_links_var = "MESH_LINKS_KML"
    kmz_deps: list[str] = []
    if plan.has_bundle:
        kmz_deps.append("$(BUNDLE_RESOLVE)")
    if plss_deps_for_kmz:
        kmz_deps.append("$(PLSS_CACHE)")
    if plan.viewshed_workspaces:
        kmz_deps.extend(f"$({site_to_ws_var[s]}_PNG) $({site_to_ws_var[s]}_GPKG)" for s in site_to_ws_var)

    if plan.emit_mesh and plan.mesh_pairs:
        lines.append("# --- Mesh geometry ---")
        for pair, var in zip(plan.mesh_pairs, mesh_pair_vars, strict=True):
            va = site_to_ws_var[pair.slug_a]
            vb = site_to_ws_var[pair.slug_b]
            lines.append(
                f"$({var}): $({va}_GPKG) $({vb}_GPKG) $({va}_PNG) $({vb}_PNG){mesh_bundle_edge}"
            )
            lines.append(f"\t$(PEAKY) mesh pairwise {pair.slug_a} {pair.slug_b} $(PRESET)")
            lines.append("")

        if mesh_depth_var and eligible_union_var:
            pairwise_completes = " ".join(f"$({v})" for v in mesh_pair_vars)
            depth_deps = (
                f"{pairwise_completes} $({eligible_union_var}){mesh_depth_extra}"
            )
            lines.append(f"$({mesh_depth_var}): {depth_deps}")
            lines.append("\t$(PEAKY) mesh depth $(PRESET)")
            lines.append("")
            lines.append(f"$({eligible_union_var}): $(COMPOSITE_ELIGIBLE)")
            lines.append("\t$(PEAKY) mesh eligible-union $(PRESET)")
            lines.append("")
        elif mesh_depth_var:
            pairwise_only = " ".join(f"$({v})" for v in mesh_pair_vars)
            depth_deps_single = f"{pairwise_only}{mesh_depth_extra}"
            lines.append(f"$({mesh_depth_var}): {depth_deps_single}")
            lines.append("\t$(PEAKY) mesh depth $(PRESET)")
            lines.append("")

        links_path = plan.mesh_links_kml
        if links_path is not None:
            st_sees = stamp_var_by_section["sites_sees"]
            gp_deps = " ".join(f"$({site_to_ws_var[s]}_GPKG)" for s in sorted(site_to_ws_var.keys()))
            lines.append(f"{mesh_links_var} ?= {_rel(plan, links_path)}")
            lines.append("")
            link_mesh_deps = f"$({st_sees}) {gp_deps}{mesh_depth_extra}"
            lines.append(f"$({mesh_links_var}): {link_mesh_deps}")
            lines.append("\t$(PEAKY) mesh links $(PRESET)")
            lines.append("")
            kmz_deps.append(f"$({mesh_links_var})")
            mesh_body = " ".join(f"$({v})" for v in mesh_pair_vars)
            mesh_body_md = mesh_body + (f" $({mesh_depth_var})" if mesh_depth_var else "")
            mesh_body_links = mesh_body_md + f" $({mesh_links_var})"
            lines.append(f"mesh: {mesh_body_links}")
            lines.append("")
            lines.append(f"mesh-pairwise: {' '.join(f'$({v})' for v in mesh_pair_vars)}")
            lines.append(f"mesh-depth:{f' $({mesh_depth_var})' if mesh_depth_var else ''}")

    st_kmz = stamp_var_by_section.get("bundle_kmz")
    if st_kmz is not None:
        kmz_deps.append(f"$({st_kmz})")

    lines.append("")
    lines.append("# --- Aggregate KMZ ---")
    extra_mesh = []
    if plan.emit_mesh:
        extra_mesh.extend(f"$({v})" for v in mesh_pair_vars)
        if mesh_depth_var:
            extra_mesh.append(f"$({mesh_depth_var})")

    kmz_full = kmz_deps + extra_mesh

    lines.append(f"$(KMZ): {' '.join(kmz_full)}")
    lines.append("\t$(PEAKY) kmz $(PRESET)")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate_makefile_text(
    *,
    preset_path: Path,
    make_root: Path | None = None,
    peaky_cmd: str = "peaky",
    preset_arg: str | None = None,
    data_dir: Path | None = None,
) -> str:
    plan = configure_preset_build(
        preset_path=preset_path,
        make_root=make_root,
        peaky_cmd=peaky_cmd,
        data_dir=data_dir,
    )
    arg = preset_arg if preset_arg is not None else plan.preset_rel
    return build_makefile_text(plan=plan, preset_arg=arg)
